### ISSUE TITLE
CRITICAL STEP ISSUE!!!!

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#115] opened 2017-09-03 01:57 UTC
**Screenshot (or video recording):** 
https://gyazo.com/51b61beebd2ce5d465a2588a374c8f57
https://gyazo.com/28cb97f35cb6d44278dca7fd01432ddd
When I try to fly up when glitched: https://gyazo.com/6caf25bae7b26136082bc9361831b220
GlitchAura: https://gyazo.com/88255aba262adaf38195cc4809d44ddc

**AntiAura version:** 11.07

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** Flux B11

**Description:** As you can see, he's hitting me OUTSIDE OF HIS LINE OF VIEW! He claims I'm RIGHT in front of him (https://prnt.sc/ggeenl) but to me I'm not! You can also see the Step thing not really dragging me back! Is the server just overloaded or is this a critical bug!

**Comment by joehot200** [comment] 2017-09-03 09:50
Closing due to not being an AntiAura issue. In all videos, AntiAuras checks are working as intended.

**Comment by joehot200** [comment] 2017-09-03 09:50
Seems to be some sort of client glitch where it isn't accepting teleport, perhaps only on your client there.

**Closed by joehot200** 2017-09-03 09:50 UTC
Labels: bug, critical, Level 3, priority

**Comment by EthanTG** [comment] 2017-09-03 12:46
welp
