### ISSUE TITLE
Bypass Fly on LiquidBounce.

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#33] opened 2017-07-25 12:49 UTC
**Info**:
- Type: Bypass
- Client: LiquidBounce b26.2 | 1.8.9
- Server: Official AntiAura Test server

**Description**:
- Bypass Fly on LiquidBounce.
- Inao (@onemoreplays) said: If under you are more than 2 blocks of air and you are not on solid block, you are flying.

**Settings**:

- Fly:
  - Bypass:
     - Vanilla (VanillaSpeed: 1.0)

**Video/Proof**:
- https://gyazo.com/135dec11753e1c5d535ead8d0cfd226e

**Comment by EthanTG** [comment] 2017-07-25 13:11
Duplicate of Issue #26

**Comment by joehot200** [comment] 2017-07-25 13:25
The Spider check allows you to travel 1.4 blocks above the ground.

The Flight check drags you down if you're above 2 blocks for more than a second.

Since your video demonstrates neither, then it seems both checks are working as intended, and so this issue can be closed.

**Closed** 2017-07-25 13:26 UTC
Labels: bypass, critical, Level 3, priority, similar
