### ISSUE TITLE
[Bug?] Entity/Player unloading?

### ISSUE THREAD

**Issue by ePocalypse** [EthanTG/AntiAura#74] opened 2017-08-07 20:50 UTC
**Screenshot (or video recording):** 
https://gyazo.com/93aa935464e140909cea139f04cb5750

**AntiAura version:**1.11

**Hacked Client (Set to N/A is none):**N/A

**Description:** From certain distance, entities like to vanish. Even players.

**Comment by EthanTG** [comment] 2017-08-07 21:31
Duplicate of issue #52. Closing.
AntiAura version is 1.11? 

@joehot200 take note of this though. The bug is existent!

**Comment by ePocalypse** [comment] 2017-08-07 22:33
https://gyazo.com/eb75268ac119bdb9463ee833199670e5

**Closed** 2017-08-09 21:48 UTC
