### ISSUE TITLE
Kicked for NoFall when in water flow

### ISSUE THREAD

**Issue by Ironic8b498** [EthanTG/AntiAura#94] opened 2017-08-16 19:11 UTC
REQUIRED FORMAT:

**Screenshot (or video recording):** 

**AntiAura version: 11.02

**Minecraft version: 1.12.1

**Hacked Client (Set to N/A if none): N/A

**Description: jump into flowing water, may not be related but logs are being spammed errors of a block being broke

failed the NoFall check. The NoFall check detected the person as using the NoFall(DistanceSpoof) hack.
He/She hit more than the threshold at 2017/08/16 14:45:15.
He/She had a ping of 600
The server TPS was at: 20.0

https://paste.md-5.net/jayolupuve.sm

**Comment by EthanTG** [comment] 2017-08-16 19:41
@Ironic8b498 IDK what happened with your formatting....

Double asterisks preceding and succeeding a word should make it bold but you didn't do that. 

I need video recording please! 

And is the paste related to the issue? Just wondering.

Duplicate of #83

**Comment by Ironic8b498** [comment] 2017-08-16 20:26
the logs is most likely not related to the water glitch, After I posted this I decided to check the other servers for spam, I believe the log has to do with the xray, since it is the only server running xray and the log came from that server. I must of deleted to much I guess if I have to report again I will leave **

**Comment by joehot200** [comment] 2017-08-16 20:57
Fixed in 11.03.

**Closed by joehot200** 2017-08-16 20:57 UTC
Labels: duplicate

**Comment by EthanTG** [comment] 2017-08-17 01:35
@joehot200 you couldn't have closed mine? ;( I feel so sad...
